### ISSUE TITLE
arm Cannot find module 'node-aead-crypto'

### ISSUE THREAD

**Issue by doofy** [hemtjanst/tradfri-mqtt#11]
` docker run -d --name tradfri-mqtt --volume /srv/tradfri/:/data/ --env TRADFRI_GATEWAY=192.168.1.100 --env TRADFRI_PSK=secret --env MQTT_ADDRESS=tcp://mosquitto:1883 hemtjanst/tradfri-mqtt:arm7`

```
module.js:557
    throw err;
    ^

Error: Cannot find module 'node-aead-crypto'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/node_modules/node-dtls-client/build/lib/AEADCrypto.js:54:47)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

**Comment by doofy** [comment]
` docker build -t hemtjanst/tradfri-mqtt:arm7 .`

```
...
Step 3/16 : RUN cd /app &&   mkdir /data &&   yarn install
 ---> Running in f3566896f0b6
yarn install v1.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info node-aead-crypto@2.1.4: The engine "node" is incompatible with this module. Expected version ">4 <10". Got "13.1.0"
info "node-aead-crypto@2.1.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
...
```

**Comment by bonan** [comment]
Try docker build with `--pull` to ensure you have the latest base image (`node:alpine`)

I forgot to push the latest version to the `hemtjanst` org at docker hub, try pulling the new one for a prebuilt version

**Comment by doofy** [comment]
thanks!
