### ISSUE TITLE
Error: Connection refused: Not authorized

### ISSUE THREAD

**Issue by Leeev** [hemtjanst/tradfri-mqtt#8]
Hi, I'm having an issue running tradfri-mqtt on a RPi - 

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/usr/lib/node_modules/tradfri-mqtt/node_modules/mqtt/lib/client.js:920:15)
    at MqttClient._handlePacket (/usr/lib/node_modules/tradfri-mqtt/node_modules/mqtt/lib/client.js:350:12)
    at work (/usr/lib/node_modules/tradfri-mqtt/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/usr/lib/node_modules/tradfri-mqtt/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/usr/lib/node_modules/tradfri-mqtt/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/lib/node_modules/tradfri-mqtt/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/usr/lib/node_modules/tradfri-mqtt/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:558:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
```
Any ideas?

**Comment by bonan** [comment]
It looks like you need authentication to access MQTT

Try setting the MQTT address to something like `tcp://username:password@127.0.0.1:1883`, either using `-a address` or setting the `MQTT_ADDRESS` environment variable

**Comment by Leeev** [comment]
Hi Bonan,
You are correct my MQTT server does have authentication (I'd forgot about that - been a while since it was set up!).
However, trying your suggestion still results in the same error. I've tried using a couple of Android apps, those (when using the username/password) can correctly login, subscribe and see MQTT messages.
Any ideas what else may be causing this?
